function rail_tester_out = fn_process_rail_data_DLL_wrapper(rail_tester_in, options)

dll_name = 'fn_process_rail_data_DLL';
function_name = dll_name;

dll_folder = fullfile(pwd,'codegen','dll', dll_name);
dll_fname = fullfile(dll_folder, [dll_name, '.dll']);
hdr_fname = fullfile(dll_folder, [dll_name, '.h']);

if ~libisloaded(dll_name)
     [notfound,warnings] = loadlibrary(dll_fname, hdr_fname);   % add 'addheader' for any extra headers if needed
end

%This is intended to be a direct swap for fn_process_rail_data. This
%wrapper function messes around with input and output to get them into a
%form suitable for processing with DLL compatible version of function,
%which will then be compiled. First task is to get DLL compilable Matlab
%version!
%First get options as structure
if nargin < 2
    options = [];
end 
options = fn_set_default_fields(options, get_default_options());

freq = randn(3,3,3);
vph = randn(3,3,3);
vgr = randn(3,3,3);
waveno = randn(3,3,3);
ms_x = randn(3,3,3);
ms_y = randn(3,3,3);
ms_z = randn(3,3,3);

[rail_tester_out.proc_data.tx_mode, rail_tester_out.proc_data.rx_mode, rail_tester_out.proc_data.tx_dir, rail_tester_out.proc_data.rx_dir, rail_tester_out.proc_data.dist, rail_tester_out.proc_data.dist_data] = ...
    fn_process_rail_data_DLL_mex( ...
        rail_tester_in.raw_data.time, ...
        rail_tester_in.raw_data.time_data, ...
        int64(rail_tester_in.raw_data.tx), ...
        int64(rail_tester_in.raw_data.rx), ...%raw data
        rail_tester_in.array.row_pos, ...
        int64(rail_tester_in.array.trans_pos), ...
        int64(rail_tester_in.array.trans_row), ...
        rail_tester_in.array.trans_pos_orientations, ...
        rail_tester_in.array.delay, ...
        int64(rail_tester_in.array.trans_node_list));

% [   rail_tester_out.proc_data.tx_mode, ...
%     rail_tester_out.proc_data.rx_mode, ...
%     rail_tester_out.proc_data.tx_dir, ...
%     rail_tester_out.proc_data.rx_dir, ...
%     rail_tester_out.proc_data.dist, ...
%     rail_tester_out.proc_data.dist_data] = calllib( dll_name, function_name, ...
%         rail_tester_in.raw_data.time, ...
%         rail_tester_in.raw_data.time_data, ...
%         int64(rail_tester_in.raw_data.tx), ...
%         int64(rail_tester_in.raw_data.rx), ...%raw data
%         rail_tester_in.array.row_pos, ...
%         int64(rail_tester_in.array.trans_pos), ...
%         int64(rail_tester_in.array.trans_row), ...
%         rail_tester_in.array.trans_pos_orientations, ...
%         rail_tester_in.array.delay, ...
%         int64(rail_tester_in.array.trans_node_list));%, ... %array
%         % freq, vph, vgr, waveno, ms_x, ms_y, ms_z, ...%these will need to be 3D arrays, where 3rd dim is mode
%         % options.freq_filter_on, options.freq_filter, ...
%         % options.freq_filter_bandwidth, options.freq_comp_for_input_signal, ...
%         % options.raw_data_ignore_pulse_echo,  options.raw_data_coupling_comp, ...
%         % options.raw_data_zero_dead_time, ... 
%         % options.ms_matrix_modes_to_use, options.ms_matrix_bidi_calc, ... 
%         % options.ms_matrix_calc_method, options.ms_matrix_calc_freqs, ... 
%         % options.ms_matrix_apply_as_time_shift, options.ms_matrix_time_step_size, ...
%         % options.ms_matrix_allow_neg_amps, ... 
%         % options.dispersion_compensation, options.warp_factor, options.manual_warps, ...
%         % options.smart_warp_ref_mode, options.smart_warp_trial_range, ...
%         % options.show_coupling_graph, options.suppress_display);
%         % 


end

function default_options  = get_default_options()
%default options - filter
default_options.freq_filter_on = 1;
default_options.freq_filter = 50e3;
default_options.freq_filter_bandwidth = 3.5e3;%filter half bandwidth to -40 dB points
default_options.freq_comp_for_input_signal = 1;
%default options - raw data
default_options.raw_data_ignore_pulse_echo = 0;
default_options.raw_data_coupling_comp = 2;
default_options.raw_data_zero_dead_time = 0;
%default options - mode shape matrix calculation - what modes and directions are included
default_options.ms_matrix_modes_to_use = [1,2,3,4];%modes used in calculation of matrices
default_options.ms_matrix_bidi_calc = 0; %turn on to include transmit in +ve direction and receive in +ve direction combos in calc
%default options - mode shape matrix calculation - single or multi-frequency
default_options.ms_matrix_calc_method = 1; %1 filter frequency; 2 linear interpolation between matrices calculated at ms_matrix_calc_freqs
default_options.ms_matrix_calc_freqs = linspace(47.5e3,52.5e3,11); %frequencies to calc mode shape matrix at for linear interpolation
%default options - mode shape matrix calculation - if you want to simulate pure time domain processing
default_options.ms_matrix_apply_as_time_shift = 0; %turn on to do freq domain processing, but applied as time rather than phase shifts
default_options.ms_matrix_time_step_size = 0; %if non-zero and doing time shifts, this sets the smallest integral multiple of time shifts allowed
default_options.ms_matrix_allow_neg_amps = 1; %if non-zero and doing time shifts, time shifts of between pi and 2pi are implemented as pi less combined with a negative amplitude
%default options - other
default_options.dispersion_compensation = 0; %turn on for dispersion compensation - not implemented!!
default_options.warp_factor = 1; %0 - no warping, 1 - use the manual warps, 2 - smart warp (I haven't tested this);
%default_options.manual_warps = ones(1, max(default_options.ms_matrix_modes_to_use));
default_options.manual_warps = [1.02,1.02,1.02,0.952]; %added this to see how it works, based on experimental result.
%default_options.manual_warps = [1.11,1.05,1.01,1.13]; %These are the warps
%for the pogo models
default_options.smart_warp_ref_mode = 3;
default_options.smart_warp_trial_range = linspace(0.9, 1.1, 21);
default_options.suppress_display = 0;
default_options.show_coupling_graph = 1;
end
