clear all
close all
addpath(genpath('.'));

%In the file benchmark.mat, I saved the following:
%   input.rail_tester - the complete rail_tester object loaded from the 
%       example file in the state it is in just before the call to 
%       fn_process_rail_data on line 1345 of the GUI (WPA_V2.m).
%   input.proc_options - the exact processing options used in 
%       fn_process_rail_data on line 1345 of the GUI (WPA_V2.m).
%   input.rail_tester - the complete rail_tester object immediately after
%       the call to fn_process_rail_data on line 1345 of the GUI (WPA_V2.m).

%This script loads that file and then confirms that the exact same output
%data (i.e. the rail_tester object) can be generated by new versions of the
%fn_process_rail_data function, e.g. one implemented as a mex file or DLL.
%Each version of the output is put into a cell array output_rail_tester{.}
%and then a sample of results is plotted from all of them - these should
%overlay

benchmark_fname = 'benchmark.mat';

%FIRST - load the benchmark output data into output_rail_tester{1}
load(benchmark_fname);
benchmark.input = input;
output_rail_tester{1} = output.rail_tester; %This is the current result exactly as obtained from the GUI as a references
clear('input', 'output');

%SECOND - process with the benchmark input data with original fn_process_rail_data
%function, which should be absolutely identical to the benchmark output
%data since it is generated using exactly the same function as in the GUI
%Local processing of benchmark input data to check same as GUI processing
output_rail_tester{2} = fn_process_rail_data_fn_wrapper(benchmark.input.rail_tester, benchmark.input.proc_options, 'original matlab');

%THIRD - new Matlab function
output_rail_tester{3} = fn_process_rail_data_fn_wrapper(benchmark.input.rail_tester, benchmark.input.proc_options, 'new matlab');

%THIRD - new Matlab function compiled into binary mex function
output_rail_tester{4} = fn_process_rail_data_fn_wrapper(benchmark.input.rail_tester, benchmark.input.proc_options, 'new mex');

%--------------------------------------------------------------------------
%Overplot the results vs. distance for a few mode combos
figure;
dmax = max(output_rail_tester{1}.proc_data.dist);

col = {'r', 'k.', 'g--', 'bo'};
for b = 1:numel(output_rail_tester)
    norm_val = max(abs(output_rail_tester{b}.proc_data.dist_data), [], 'all');
    tmp = 20 * log10(abs(output_rail_tester{b}.proc_data.dist_data) / norm_val);
    for direction = [-1:1]
        k = find((output_rail_tester{b}.proc_data.tx_dir == direction) & (output_rail_tester{b}.proc_data.rx_dir == direction));
        if numel(k)>3
            k = k(1:3);
        end
        for i = 1:numel(k)
            subplot(numel(k), 2, i * 2 + (direction + 1) / 2 - 1);
            plot(output_rail_tester{b}.proc_data.dist * direction, tmp(:, k(i)), col{b});
            hold on;
            ylim([-40, 0]);
            if i < numel(k)
                set(gca, 'XTickLabel', []);
            end
            if direction == 1
                if b == 1
                    text(dmax / 2, -20, sprintf('%i-%i', output_rail_tester{b}.proc_data.tx_mode(k(i)), output_rail_tester{b}.proc_data.rx_mode(k(i))));
                end
                xlim([0, dmax])
            else
                xlim([-dmax, 0])
            end
        end
    end
end
